### ISSUE TITLE
Simple map, csum! example - 'view' has no matching method

### ISSUE THREAD

**Issue by gminorcoles** [rened/FunctionalData.jl#1]
Hi,
 I got Julia by downloading the latest Juno/Julia bundle. Then I did Pkg.add("FunctionalData). I typed a = randn(10,100000), defined cmap!(), which runs when I call it directly. I then tried to run lmap(a,cmap!) but I get this error:

exception on 1: ERROR: `view` has no method matching view(::Array{Any,1}, ::Int6
4)
 in map at C:\Users\admin.julia\v0.3\FunctionalData\src\computing.jl:50
 in mapper at C:\Users\admin.julia\v0.3\FunctionalData\src\computing.jl:217
 in g at C:\Users\admin.julia\v0.3\FunctionalData\src\computing.jl:257
 in anonymous at multi.jl:660
 in run_work_thunk at multi.jl:621
 in remotecall_fetch at multi.jl:694
 in remotecall_fetch at multi.jl:709
 in anonymous at task.jl:1365
ERROR: `ndims` has no method matching ndims(::MethodError)
 in flatten at C:\Users\admin.julia\v0.3\FunctionalData\src\dataflow.jl:110
 in pmap_exec at C:\Users\admin.julia\v0.3\FunctionalData\src\computing.jl:253
 in pmap_internal at C:\Users\admin.julia\v0.3\FunctionalData\src\computing.jl:
258
 in lmap at C:\Users\admin.julia\v0.3\FunctionalData\src\computing.jl:280

This is windows 64-bit. I tried Julia in 2013 but I wasn't ready and now I am trying again. How can I figure out where Julia thinks the function "view" lives? I am a Matlab user so I would be accustomed to using "which". 

thx
george

**Comment by rened** [comment]
Hi! Could you please try the following, this should work:

``` jl
addprocs(3)
using FunctionalData
csum(x) = (for i = 2:length(x) x[i] += x[i-1] end; x)
a = rand(10,100)
lmap(a, csum)
```

Could you please post your code snippet, there must be a small difference somewhere.
Regarding `which`, this works slightly different in Julia, and you have several options: in the REPL (the terminal programm you are in after you started julia), run 

``` jl
using FunctionalData
```

and then type `view(` and hit TAB - you will get a list of possible definitions. 
The same output can be shown with `methods(view)`.
You will see that there are distinct definitions for different parameter types, so to find a specific one you can e.g. use `@which`:

``` jl
@which view([1 2 3])
```

But for this specific case you should not need to dig into the code, it is rather the case that I should provide more detailed parameter checking / documentation ;-). Given your code I will see what I have to fix.

**Comment by gminorcoles** [comment]
Ok I just got home, I am trying this out on my home computer. I started julia with 6 processors - is that the same as addprocs? The error I get is not that informative. @which lmap(a,csum) points to the right place though. 

c:\tools\julia\juno-windows-x64\windows64\resources\app\julia\bin>julia -p 6
               _
   _       _ _(_)_     |  A fresh approach to technical computing

julia> using FunctionalData

julia> csum(x) = (for i = 2:length(x) x[i] += x[i-1] end; x)
csum (generic function with 1 method)

julia> a = rand(10,100)
10x100 Array{Float64,2}:

julia> lmap(a,csum)
ERROR: BoundsError()
 in getindex at range.jl:258 (repeats 2 times)

julia> @which lmap(a,csum)
lmap(a,f) at C:\Users\admin.julia\v0.3\FunctionalData\src\computing.jl:280

**Comment by rened** [comment]
Could you please try with the 0.0.4 version of FunctionalData? Simply run

``` jl
Pkg.update()
```

A subsequent `Pkg.status("FunctionalData")` should show 0.0.4. 
I could reproduce the bug you saw, should be fixed now, thanks for filing this issue!

**Comment by gminorcoles** [comment]
That worked. Thanks for responding to the issue. I look forward to trying the ideas in this package. I am a matlab user hoping that Julia might someday save me, and how to do parallel and distributed tasks is a key issue for me.

**Comment by rened** [comment]
Glad it worked! Yes, parallel programming is considerably easier in Julia. I'll ping you when the manual section on the different *map variants is done!
